global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sat-prep-server'
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/api/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
